### ISSUE TITLE
Data not persisting in the database. 

### ISSUE THREAD

**Issue by gekkaBee** [tfrancoi/odoo_import_example#1]
The data's are not persisting in the database. The id's are taken but the data are not reflected.

**Comment by tfrancoi** [comment]
Hello, thank you for your feedback.
Those example are meant for odoo 11, if you test them with another version it's very likelikly that it won't work

If the id have been taken but there is nothing in the database it's probably because the transaction rollback due to an error. You should be able to see those error in the output or in the log file of odoo.
